export const FETCH_USERS = 'USERS/FETCH_USERS';
export const SET_USER_ID = 'USERS/SET_USER_ID';
export const FETCH_USER_POSTS = 'POSTS/FETCH_USER_POSTS';
export const SET_USER_POST = 'POSTS/SET_USER_POST';
export const FETCH_POST_COMMENTS = 'COMMENTS/FETCH_POST_COMMENTS';
export const SHOW_MESSAGE = 'APP/SHOW_MESSAGE';
export const SHOW_MODAL_CREATE = 'APP/SHOW_MODAL_CREATE';
export const SHOW_MODAL_EDIT = 'APP/SHOW_MODAL_EDIT';
